# Generated by Django 5.0.2 on 2025-03-24 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(choices=[('basic', 'Basic VIP Access'), ('quarterly', 'Quarterly Plan'), ('yearly', 'Yearly Plan')], max_length=20, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_note', models.CharField(blank=True, max_length=100, null=True)),
                ('duration', models.CharField(max_length=50)),
                ('features', models.TextField(help_text='Use comma-separated values')),
            ],
        ),
    ]
