# Generated by Django 5.0.2 on 2025-03-24 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_subscriptionplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='plan_type',
            field=models.CharField(choices=[('basic', 'Basic VIP Access'), ('quarterly', 'Quarterly Plan'), ('yearly', 'Yearly Plan'), ('vip', 'VIP Plan')], max_length=20, unique=True),
        ),
    ]
