# Generated by Django 5.0.2 on 2025-03-24 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_subscriptionplan_plan_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountedPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=50)),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discounted_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_note', models.CharField(blank=True, max_length=100, null=True)),
                ('is_popular', models.BooleanField(default=False)),
                ('highlight_text', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Discounted Plan',
                'verbose_name_plural': 'Discounted Plans',
            },
        ),
    ]
