# Generated by Django 5.0.2 on 2025-04-15 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_subscription_cryptomus_recurring_uuid_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('crypto', 'Crypto'), ('card', 'Card'), ('paypal', 'PayPal'), ('bank', 'Bank Transfer')], default='crypto', max_length=20),
        ),
    ]
