# Generated by Django 5.0.2 on 2025-05-17 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.CharField(choices=[('basic', 'Basic VIP Access'), ('quarterly', 'Quarterly Plan'), ('six_month', 'Six-Month Plan'), ('yearly', 'Yearly Plan')], max_length=20),
        ),
    ]
