# Generated by Django 5.2.6 on 2025-09-16 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_subscription_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
