# Generated by Django 5.2.6 on 2025-09-17 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_remove_payment_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('partial', 'Partial')], default='pending', max_length=10),
        ),
    ]
