# Generated by Django 5.2.6 on 2025-09-18 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0012_alter_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('crypto', 'Crypto'), ('card', 'Card'), ('paypal', 'PayPal'), ('bank', 'Bank Transfer'), ('deposit', 'Deposit')], default='crypto', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='payments.subscription'),
        ),
    ]
