# Generated by Django 5.2.6 on 2025-09-19 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0014_payment_payment_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('crypto', 'Crypto'), ('card', 'Card'), ('paypal', 'PayPal'), ('bank', 'Bank Transfer'), ('deposit', 'Deposit'), ('withdraw', 'Withdraw')], default='crypto', max_length=20),
        ),
    ]
