# Generated by Django 5.2.6 on 2025-09-19 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0015_alter_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
