# Generated by Django 5.2.6 on 2025-09-28 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0016_payment_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='days',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
