# Generated by Django 5.2.6 on 2025-09-28 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0017_subscriptionplan_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='days',
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='months',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
