# Generated by Django 5.2.7 on 2025-10-12 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0018_remove_subscriptionplan_days_subscriptionplan_months'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='want_to_upgrade',
            field=models.BooleanField(default=False),
        ),
    ]
