# Generated by Django 5.2.7 on 2025-10-13 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0019_subscription_want_to_upgrade'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='pre_subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pre_sub', to='payments.subscription'),
        ),
    ]
