# Generated by Django 5.2.7 on 2025-10-13 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0020_payment_pre_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='pre_subscription',
        ),
        migrations.AddField(
            model_name='payment',
            name='new_subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='new_sub', to='payments.subscription'),
        ),
    ]
