# Generated by Django 5.2.7 on 2025-10-13 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0021_remove_payment_pre_subscription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='new_subscription',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
