# Generated by Django 5.2.7 on 2025-10-13 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0022_alter_payment_new_subscription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='new_subscription',
            new_name='pre_subscription',
        ),
    ]
