# Generated by Django 5.2.7 on 2025-10-19 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0023_rename_new_subscription_payment_pre_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='next_subscription',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
