# Generated by Django 5.0.2 on 2025-03-25 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_email_verification_token_user_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='awaiting_verification',
            field=models.BooleanField(default=False),
        ),
    ]
