# Generated by Django 5.0.2 on 2025-04-14 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_awaiting_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='crypto_duration',
            field=models.CharField(blank=True, choices=[('less_than_1_year', 'Less than 1 year'), ('1_2_years', '1–2 years'), ('2_3_years', '2–3 years'), ('3_5_years', '3–5 years'), ('5_plus_years', '5+ years')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='crypto_experience',
            field=models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='interests',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='user',
            name='investment_budget',
            field=models.CharField(blank=True, choices=[('<$100', '<$100'), ('$100–$500', '$100–$500'), ('$500–$1,000', '$500–$1,000'), ('$1,000–$5,000', '$1,000–$5,000'), ('$5,000+', '$5,000+')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='learning_preference',
            field=models.CharField(blank=True, choices=[('short_videos', 'Short videos'), ('articles', 'Articles'), ('telegram_updates', 'Telegram updates'), ('courses', 'Courses'), ('1_on_1_mentorship', '1-on-1 mentorship')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='main_goal',
            field=models.CharField(blank=True, choices=[('learn_understand_basics', 'Learn & understand the basics'), ('build_long_term_portfolio', 'Build a long-term portfolio'), ('get_signals_trading_strategies', 'Get signals & trading strategies'), ('stay_updated_latest_trends', 'Stay updated with the latest trends'), ('join_premium_community', 'Join a premium community')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='preferences_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='trading_platforms',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='user',
            name='vip_interest',
            field=models.CharField(blank=True, choices=[('yes_i_want_premium_insights', 'Yes, I want premium insights'), ('maybe_tell_me_more_later', 'Maybe, tell me more later'), ('no_just_free_content_for_now', 'No, just free content for now')], max_length=50, null=True),
        ),
    ]
