# Generated by Django 5.0.2 on 2025-04-14 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_crypto_duration_user_crypto_experience_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='crypto_duration',
        ),
        migrations.RemoveField(
            model_name='user',
            name='crypto_experience',
        ),
        migrations.RemoveField(
            model_name='user',
            name='interests',
        ),
        migrations.RemoveField(
            model_name='user',
            name='investment_budget',
        ),
        migrations.RemoveField(
            model_name='user',
            name='learning_preference',
        ),
        migrations.RemoveField(
            model_name='user',
            name='main_goal',
        ),
        migrations.RemoveField(
            model_name='user',
            name='preferences_completed',
        ),
        migrations.RemoveField(
            model_name='user',
            name='trading_platforms',
        ),
        migrations.RemoveField(
            model_name='user',
            name='vip_interest',
        ),
    ]
