# Generated by Django 5.0.2 on 2025-04-14 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_user_crypto_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='crypto_experience',
            field=models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='crypto_goal',
            field=models.CharField(blank=True, choices=[('learn_basics', 'Learn & understand the basics'), ('long_term_portfolio', 'Build a long-term portfolio'), ('signals_trading', 'Get signals & trading strategies'), ('stay_updated', 'Stay updated with the latest trends'), ('premium_community', 'Join a premium community')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='crypto_years_active',
            field=models.CharField(blank=True, choices=[('<1', 'Less than 1 year'), ('1-2', '1–2 years'), ('2-3', '2–3 years'), ('3-5', '3–5 years'), ('5+', '5+ years')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='interests',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='user',
            name='learning_preference',
            field=models.CharField(blank=True, choices=[('short_videos', 'Short videos'), ('articles', 'Articles'), ('telegram_updates', 'Telegram updates'), ('courses', 'Courses'), ('mentorship', '1-on-1 mentorship')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='monthly_budget',
            field=models.CharField(blank=True, choices=[('<100', '<$100'), ('100-500', '$100–$500'), ('500-1000', '$500–$1,000'), ('1000-5000', '$1,000–$5,000'), ('5000+', '$5,000+')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='trading_platforms',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='user',
            name='vip_interest',
            field=models.CharField(blank=True, choices=[('yes', 'Yes, I want premium insights'), ('maybe', 'Maybe, tell me more later'), ('no', 'No, just free content for now')], max_length=30, null=True),
        ),
    ]
