# Generated by Django 5.2.6 on 2025-09-16 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_email_alter_user_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_address', models.CharField(max_length=100, unique=True)),
                ('wallet_type', models.CharField(choices=[('metamask', 'MetaMask'), ('trust_wallet', 'Trust Wallet'), ('coinbase_wallet', 'Coinbase Wallet'), ('ledger', 'Ledger'), ('trezor', 'Trezor'), ('other', 'Other')], default='other', max_length=20)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'wallet_address')},
            },
        ),
    ]
