# Generated by Django 5.2.6 on 2025-09-17 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_userwallet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserWallet',
        ),
    ]
