# Generated by Django 5.0.2 on 2025-03-24 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntroductionContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='What is CryptoZen?', max_length=200)),
                ('video', models.FileField(upload_to='introduction/videos/')),
                ('poster_desktop', models.ImageField(upload_to='introduction/posters/desktop/')),
                ('poster_mobile', models.ImageField(upload_to='introduction/posters/mobile/')),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Introduction Section Content',
                'verbose_name_plural': 'Introduction Section Contents',
            },
        ),
    ]
