# Generated by Django 5.0.2 on 2025-07-28 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referrallink',
            name='url',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
    ]
