# Generated by Django 5.0.2 on 2025-08-01 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0003_referrallink_join_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='referrallink',
            name='collab_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
