# Generated by Django 5.0.2 on 2025-08-01 17:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0004_referrallink_collab_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReferralLink',
            new_name='CollabLink',
        ),
    ]
