# Generated by Django 5.0.2 on 2025-08-02 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0005_rename_referrallink_collablink'),
    ]

    operations = [
        migrations.AddField(
            model_name='collablink',
            name='cost_from_join_users',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
