# Generated by Django 5.2.7 on 2025-10-06 11:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0006_collablink_cost_from_join_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collablink',
            name='url',
        ),
        migrations.AlterField(
            model_name='collablink',
            name='join_users',
            field=models.ManyToManyField(blank=True, related_name='joined_collabs', to=settings.AUTH_USER_MODEL),
        ),
    ]
