# Generated by Django 5.2.7 on 2025-10-08 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0007_remove_collablink_url_alter_collablink_join_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='collablink',
            name='reward',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
