# Generated by Django 5.2.7 on 2025-10-08 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0008_collablink_reward'),
    ]

    operations = [
        migrations.AddField(
            model_name='collablink',
            name='code',
            field=models.CharField(default='30cQTD1UER', max_length=10),
        ),
        migrations.AlterField(
            model_name='collablink',
            name='cost_from_join_users',
            field=models.PositiveIntegerField(default=20),
        ),
    ]
