# Generated by Django 5.2.7 on 2025-10-08 13:06

import collab.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0010_alter_collablink_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collablink',
            name='code',
            field=models.CharField(default=collab.models.generate_referral_code, max_length=10),
        ),
    ]
