# Generated by Django 5.2.7 on 2025-10-08 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0011_alter_collablink_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='collablink',
            name='pro_cost_available',
            field=models.BooleanField(default=False),
        ),
    ]
