# Generated by Django 5.2.7 on 2025-10-10 18:27

import collab.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0012_collablink_pro_cost_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collablink',
            name='code',
            field=models.CharField(default=collab.models.generate_referral_code, max_length=10),
        ),
    ]
