# Generated by Django 5.0.2 on 2025-03-23 19:39

import contact.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_usercomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercomment',
            name='image_url',
        ),
        migrations.AddField(
            model_name='usercomment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=contact.models.comment_image_upload_path),
        ),
    ]
