# Generated by Django 5.2.7 on 2025-10-18 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_remove_usercomment_image_url_usercomment_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='message_type',
            field=models.CharField(choices=[('withdraw', 'Withdraw'), ('contact', 'Contact')], default='contact', max_length=150),
        ),
    ]
