# Generated by Django 5.0.2 on 2025-05-19 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification_is_global_notification_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='show',
            field=models.BooleanField(default=True),
        ),
    ]
